AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
